version: '3.3'
services:
  postgres:
    container_name: postgres
    build: ./docker/postgres
    image: luizmoratelli/postgres
    environment:
      - POSTGRES_DB=locar
      - POSTGRES_USER=postgres
      - TZ=GMT
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgresql-data: